"""New ADR024 evidence set, no replacement of ADR023 pins or artifacts."""
import hashlib
import importlib.util
import json
from pathlib import Path
import sys

ROOT=Path('/home/DHB/Documents/NANFO')
sys.path.insert(0,str(ROOT))
from deploy import release_manifest as r
dest=ROOT/'docs/project/CompletionProgram/DeploymentEvidence-ADR024'
dest.mkdir(mode=0o700,exist_ok=True)
snapshot=Path('/tmp/opencode/nanfo-adr023-frozen-ei7ulj7m')
run=Path('/tmp/opencode/nanfo-deploy-verify-5bv6nj_5')
spec=importlib.util.spec_from_file_location('preserve','/tmp/opencode/preserve_adr023.py')
preserve=importlib.util.module_from_spec(spec)
spec.loader.exec_module(preserve)
preserve.DEST=dest
preserve.campaign('distributed',run,snapshot)
def save(name,raw):
    path=dest/name
    if path.exists(): assert path.read_bytes()==raw
    else:r.publish(path,raw)
result=json.loads((run/'evidence/result.json').read_bytes())
assert result['core_passed'] and result['counts']=={'passed':29,'failed':0,'blocked':4,'pending':0}
images=result['cases']['locked_container_build']['detail']['images']
images={**images,'fleet':{'id':'sha256:ff58e0c92eb0a3d5ba038efb0ea9c4c225fa04b972da0c29c0309175ff0b5d0b','os':'linux','architecture':'amd64'}}
save('images.json',r.canonical(images))
hashes=json.loads((snapshot/'source-snapshot.json').read_bytes())
safe={}
for name,digest in hashes.items():
    try:r.safe_name(name)
    except r.EvidenceError:continue
    safe[name]=digest
save('release-build.json',r.canonical({'image_id':images['api']['id'],'images':images,'source_sha256':safe,
    'host_site_packages_used':False,'scope':'ADR024 source matched distributed runtime;341 installed files'}))
manifest=r.create_manifest(snapshot,dest,['release-build.json'])
save('release.json',r.canonical(manifest))
r.verify_manifest(manifest,snapshot,dest)
archive=dest/'distributed-evidence.tar'
if not archive.exists():
    digest=r.export_bundle(dest/'release.json',run,archive)
    r.verify_bundle_bytes(archive.read_bytes(),digest)
    save('distributed-archive-sha256.json',r.canonical({'sha256':digest}))
for name,source in (
    ('fleet-build-result.json','/tmp/opencode/nanfo-adr023-fleet-build-mdwd31s8/result.json'),
    ('fleet-build.log','/tmp/opencode/nanfo-adr023-fleet-build-mdwd31s8/build.log'),
    ('installed-smoke.json','/tmp/opencode/nanfo-adr023-health-final-probe-yb2dkj9p/result.json'),
    ('installed-smoke-probe.py','/tmp/opencode/adr023_health_final_probe.py'),
    ('installed-image-check.py','/tmp/opencode/adr023_health_final_image_check.py'),
    ('confined-qualification.json','/tmp/opencode/nanfo-adr024-deploy-qualification-f9o5h_18/result.json'),
    ('confined-qualification.stdout','/tmp/opencode/nanfo-adr024-deploy-qualification-f9o5h_18/qualify.stdout'),
    ('confined-qualification.py','/tmp/opencode/adr024_confined_qualification.py'),
    ('qualified-registry.json','/tmp/opencode/nanfo-adr024-deploy-qualification-f9o5h_18/registry.json'),
):save(name,Path(source).read_bytes())
# Evidence already generated by the qualified live campaign; attributed, not rerun.
for name in ('result.json','qualification.json','cleanup.json','evidence-audit.json'):
    save('attributed-continuous-'+name,Path('/tmp/opencode/nanfo-live-acceptance-7ngrbdgv',name).read_bytes())
old=json.loads(Path('/tmp/opencode/nanfo-adr023-frozen-yvofvp9n/source-snapshot.json').read_bytes())
diff=[{'path':p,'previous_sha256':old.get(p),'current_sha256':hashes.get(p)} for p in sorted(old.keys()|hashes.keys()) if old.get(p)!=hashes.get(p)]
save('changes-from-adr023.json',r.canonical(diff))
save('summary.json',r.canonical({'schema':'0027','distributed':result['counts'],'deployment_tests':{'passed':216,'failed':0},
    'installed_smoke':{'passed':20,'failed':0},'confined_raw_benchmark_qualification':{'passed':1,'failed':0},
    'qualified_model':'77dae44acab722a5a6a2e87d952a6cca65e1c4eea102a089830a8401b521d614',
    'fresh_live_observation_readiness':False,'native_autonomy':'blocked','physical_qualification':False,
    'new_training_or_lab':False,'images':images,'source_drift':json.loads((dest/'distributed-source-drift.json').read_bytes())}))
save('export.py',Path(__file__).read_bytes())
save('checksums.json',r.canonical({p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in dest.iterdir() if p.is_file() and p.name!='checksums.json'}))
print(json.dumps({'counts':result['counts'],'backend':images['api']['id'],'fleet':images['fleet']['id']}))
