"""Real PostgreSQL migration contract (ADR-028 BE-DB); enabled only for MIGRATION_TEST_DSN.

Runs the real alembic/env.py (per-revision transactions, lock_timeout, autocommit
CONCURRENTLY blocks) in a disposable schema through ``config.attributes["connection"]``:
``upgrade head`` then ``alembic check`` must report no changes, and ``downgrade 0029``
then ``upgrade head`` must succeed. Data tests cover migration 0030's dedupe, backfill,
NOT VALID handling, spatial delta storage and the historical downgrade evidence guards.
"""

from __future__ import annotations

import json
import os
import uuid
from datetime import UTC, datetime, timedelta
from pathlib import Path
from types import SimpleNamespace

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import create_engine, text
from sqlalchemy.engine import make_url
from sqlalchemy.exc import DBAPIError

from app.modules.alert.scope import scope_columns

pytestmark = pytest.mark.skipif(not os.environ.get("MIGRATION_TEST_DSN"), reason="MIGRATION_TEST_DSN not configured")
BACKEND = Path(__file__).resolve().parents[2]
NOW = datetime(2026, 9, 24, 12, 0, tzinfo=UTC)
CONSTRAINTS_0030 = (
    "fk_report_outbox_report", "fk_alert_observations_detector", "fk_autonomous_executions_resource",
    "ck_alerts_status", "ck_intents_status", "ck_intents_queue_status", "ck_simulations_state",
    "ck_simulations_status", "ck_reports_status", "ck_intent_executions_phase", "ck_experimental_action_phase",
    "ck_experimental_run_phase", "ck_org_members_org_role", "ck_plugins_queue_status",
)
CONCURRENT_INDEXES = (
    "ix_telemetry_records_device_observed", "ix_telemetry_records_observed_at_brin", "ix_audit_logs_org_timestamp",
    "ix_alerts_workspace_updated", "ix_alerts_network_id", "ix_alert_consumed_events_alert_id",
    "ix_alert_observations_detector_key", "ix_alert_observations_observed_at_brin",
)


@pytest.fixture
def database():
    url = make_url(os.environ["MIGRATION_TEST_DSN"]).set(drivername="postgresql+psycopg2")
    engine = create_engine(url)
    schema = "migration_test_" + uuid.uuid4().hex
    with engine.begin() as admin:
        admin.execute(text(f'CREATE SCHEMA "{schema}"'))
    connection = engine.connect()
    try:
        connection.execute(text(f'SET search_path TO "{schema}"'))  # session scope: survives commits
        connection.commit()
        config = Config()  # no ini file: env.py must not reconfigure the test session's logging
        config.set_main_option("script_location", str(BACKEND / "alembic"))
        config.attributes["connection"] = connection
        yield SimpleNamespace(engine=engine, connection=connection, config=config, schema=schema)
    finally:
        connection.rollback()
        connection.close()
        with engine.begin() as admin:
            admin.execute(text(f'DROP SCHEMA "{schema}" CASCADE'))
        engine.dispose()


def run(db, statement: str, **parameters):
    result = db.connection.execute(text(statement), parameters)
    rows = result.all() if result.returns_rows else None
    db.connection.commit()
    return rows


def version(db) -> str:
    return run(db, "SELECT version_num FROM alembic_version")[0][0]


def validated(db) -> dict[str, bool]:
    rows = run(db, "SELECT conname, convalidated FROM pg_constraint "
                   "WHERE connamespace = current_schema()::regnamespace AND conname = ANY(:names)",
               names=list(CONSTRAINTS_0030))
    return dict(rows)


def test_upgrade_head_matches_models_and_downgrade_to_0029_round_trips(database, monkeypatch):
    monkeypatch.setenv("NANFO_MIGRATION_LOCK_TIMEOUT", "5s")
    command.upgrade(database.config, "head")
    assert version(database) == "0030"
    command.check(database.config)  # AutogenerateDiffsDetected on any model/schema drift
    assert validated(database) == dict.fromkeys(CONSTRAINTS_0030, True)
    indexes = dict(run(database, "SELECT c.relname, i.indisvalid FROM pg_index i JOIN pg_class c "
                                 "ON c.oid = i.indexrelid WHERE c.relname = ANY(:names) "
                                 "AND c.relnamespace = current_schema()::regnamespace",
                       names=list(CONCURRENT_INDEXES)))
    assert indexes == dict.fromkeys(CONCURRENT_INDEXES, True)
    # The session keeps the configured lock_timeout after the suspended concurrent block.
    assert run(database, "SHOW lock_timeout")[0][0] == "5s"

    command.downgrade(database.config, "0029")
    assert version(database) == "0029"
    assert run(database, "SELECT to_regclass('ix_users_email') IS NOT NULL")[0][0] is True
    command.upgrade(database.config, "head")
    assert version(database) == "0030"
    command.check(database.config)


def test_upgrade_is_idempotent_when_the_version_bump_was_lost(database):
    command.upgrade(database.config, "head")
    # Simulates a failure after the concurrent phase: schema changed, version still 0029.
    run(database, "UPDATE alembic_version SET version_num = '0029'")
    command.upgrade(database.config, "head")
    assert version(database) == "0030"
    command.check(database.config)


def test_interrupted_concurrent_build_leftover_is_rebuilt(database):
    command.upgrade(database.config, "0029")
    device = uuid.uuid4()
    for _ in range(2):
        run(database, "INSERT INTO telemetry_records (event_id, correlation_id, device_id, network_id, workspace_id, "
                      "metric, value, observed_at, source) VALUES (:event, :event, :device, :device, :device, "
                      "'cpu', 1, :now, 'test')", event=uuid.uuid4(), device=device, now=NOW)
    with database.engine.connect().execution_options(isolation_level="AUTOCOMMIT") as autocommit:
        autocommit.execute(text(f'SET search_path TO "{database.schema}"'))
        with pytest.raises(DBAPIError):  # a failed concurrent build leaves an INVALID index
            autocommit.execute(text("CREATE UNIQUE INDEX CONCURRENTLY ix_telemetry_records_device_observed "
                                    "ON telemetry_records (device_id)"))
    assert run(database, "SELECT indisvalid FROM pg_index WHERE indexrelid = "
                         "to_regclass('ix_telemetry_records_device_observed')")[0][0] is False
    command.upgrade(database.config, "head")
    valid, unique, definition = run(database, "SELECT i.indisvalid, i.indisunique, pg_get_indexdef(i.indexrelid) "
                                              "FROM pg_index i WHERE i.indexrelid = "
                                              "to_regclass('ix_telemetry_records_device_observed')")[0]
    assert valid and not unique and "observed_at DESC, record_id DESC" in definition


def _seed_0029(db) -> SimpleNamespace:
    workspace, other_workspace, network, org = (uuid.uuid4() for _ in range(4))
    seeded = SimpleNamespace(workspace=workspace, network=network, org=org, intents=[], alerts={})
    for offset in range(3):  # three rows share one (workspace, key); the earliest keeps it
        intent_id = uuid.uuid4()
        seeded.intents.append(intent_id)
        run(db, "INSERT INTO intents (intent_id, workspace_id, intent_kind, idempotency_key, correlation_id, "
                "requested_by_user_id, requested_at, created_at) VALUES (:id, :ws, 'reroute_path', 'key-1', :id, "
                "'actor', :at, :at)", id=intent_id, ws=workspace, at=NOW + timedelta(seconds=offset))
    seeded.other_intent = uuid.uuid4()
    run(db, "INSERT INTO intents (intent_id, workspace_id, intent_kind, idempotency_key, correlation_id, "
            "requested_by_user_id, requested_at) VALUES (:id, :ws, 'reroute_path', 'key-1', :id, 'actor', :at)",
        id=seeded.other_intent, ws=other_workspace, at=NOW)

    run(db, "INSERT INTO networks (network_id, workspace_id, name) VALUES (:id, :ws, 'n')", id=network, ws=workspace)
    seeded.buildings = []
    for offset, deleted in ((0, None), (5, None), (9, NOW)):  # older active, newest active, already deleted
        building_id = uuid.uuid4()
        seeded.buildings.append(building_id)
        run(db, "INSERT INTO campus_buildings (campus_building_id, network_id, building_id, campus_key, building_key, "
                "label, geometry, x, z, base_y, width, depth, height, floors, updated_at, deleted_at) VALUES "
                "(:id, :net, 'B1', 'c', 'b', 'l', 'box', 0, 0, 0, 1, 1, 1, 1, :at, :deleted)",
            id=building_id, net=network, at=NOW + timedelta(seconds=offset), deleted=deleted)

    other = uuid.uuid4()
    payloads = [
        {"workspace_id": str(workspace), "network_id": str(network), "org_id": str(org)},
        {"scope": {"workspace_id": str(workspace), "network_id": str(network)}},
        {"workspace_id": None, "scope": {"workspace_id": str(workspace)}},
        {"workspace_id": str(workspace), "scope": {"workspace_id": str(other)}},
        {"workspace_id": "not-a-uuid", "network_id": str(network)},
        {"workspace_id": 12345},
        [1, 2],
        {"org_id": "{" + str(org).upper() + "}"},
        {"network_id": "urn:uuid:" + str(network)},
        {"workspace_id": workspace.hex},
        {},
        {"scope": "not-an-object", "org_id": str(org)},
        {"workspace_id": ""},
        {"network_id": None, "scope": {"network_id": None}},
    ]
    for payload in payloads:
        alert_id = uuid.uuid4()
        seeded.alerts[alert_id] = payload
        run(db, "INSERT INTO alerts (alert_id, alert_key, source, correlation_id, payload) "
                "VALUES (:id, 'k', 'test', :id, CAST(:payload AS jsonb))", id=alert_id, payload=json.dumps(payload))

    run(db, "INSERT INTO report_outbox (event_id, report_id, status_version, envelope) "
            "VALUES (:id, :missing, 1, '{}')", id=uuid.uuid4(), missing=uuid.uuid4())  # orphan (retention)
    run(db, "INSERT INTO organizations (org_id, name, slug) VALUES (:org, 'o', :slug)", org=org, slug=org.hex)
    run(db, "INSERT INTO org_members (org_id, user_id, org_role) VALUES (:org, :user, 'Viewer')",
        org=org, user=uuid.uuid4())
    run(db, "INSERT INTO network_spatial_scenes (network_id, revision, scene) VALUES (:net, 1, '{}')", net=network)
    run(db, "INSERT INTO network_spatial_scene_revisions (network_id, revision, scene, origin) "
            "VALUES (:net, 1, '{}', 'baseline')", net=network)
    return seeded


def test_0030_fixes_data_and_keeps_violating_constraints_not_valid(database, monkeypatch, caplog):
    command.upgrade(database.config, "0029")
    seeded = _seed_0029(database)
    monkeypatch.setenv("NANFO_MIGRATION_BATCH_SIZE", "2")  # several keyset batches
    caplog.set_level("INFO", logger="alembic.migration.0030")
    command.upgrade(database.config, "head")

    first, second, third = seeded.intents
    keys = dict(run(database, "SELECT intent_id, idempotency_key FROM intents"))
    assert keys[first] == "key-1" and keys[seeded.other_intent] == "key-1"
    assert keys[second] == f"key-1~dup~{second}" and keys[third] == f"key-1~dup~{third}"
    assert "Renamed 2 duplicate intent idempotency keys" in caplog.text
    with pytest.raises(DBAPIError, match="uq_intents_workspace_idempotency"):
        run(database, "INSERT INTO intents (workspace_id, intent_kind, idempotency_key, correlation_id, "
                      "requested_by_user_id, requested_at) VALUES (:ws, 'x', 'key-1', :ws, 'actor', now())",
            ws=seeded.workspace)
    database.connection.rollback()

    buildings = {row[0]: row[1:] for row in run(database, "SELECT campus_building_id, deleted_at, updated_at "
                                                           "FROM campus_buildings")}
    older, newest, deleted = seeded.buildings
    assert buildings[newest][0] is None and buildings[older][0] is not None
    assert buildings[older][1] == buildings[older][0] and buildings[deleted][0] == NOW

    columns = {row[0]: dict(zip(("org_id", "workspace_id", "network_id"), row[1:], strict=True))
               for row in run(database, "SELECT alert_id, org_id, workspace_id, network_id FROM alerts")}
    for alert_id, payload in seeded.alerts.items():  # the SQL backfill mirrors the Python rule exactly
        assert columns[alert_id] == scope_columns(payload), payload

    state = validated(database)
    assert state.pop("fk_report_outbox_report") is False  # orphaned by report retention before 0030
    assert state.pop("ck_org_members_org_role") is False  # 'Viewer' row predates the CHECK
    assert all(state.values()), state
    assert "left NOT VALID" in caplog.text
    with pytest.raises(DBAPIError, match="fk_report_outbox_report"):  # still enforced for new rows
        run(database, "INSERT INTO report_outbox (event_id, report_id, status_version, envelope) "
                      "VALUES (:id, :id, 1, '{}')", id=uuid.uuid4())
    database.connection.rollback()
    command.check(database.config)


def test_spatial_delta_storage_keeps_immutability_and_blocks_downgrade(database):
    command.upgrade(database.config, "0029")
    seeded = _seed_0029(database)
    command.upgrade(database.config, "head")
    triggers = {row[0] for row in run(database, "SELECT tgname FROM pg_trigger WHERE NOT tgisinternal AND "
                                                "tgrelid = 'network_spatial_scene_revisions'::regclass")}
    assert triggers == {"spatial_scene_history_immutable", "spatial_scene_history_no_truncate"}
    assert run(database, "SELECT storage_kind FROM network_spatial_scene_revisions")[0][0] == "full"
    with pytest.raises(DBAPIError, match="spatial scene history is immutable"):
        run(database, "UPDATE network_spatial_scene_revisions SET origin = 'baseline'")
    database.connection.rollback()
    with pytest.raises(DBAPIError, match="ck_spatial_history_body"):
        run(database, "INSERT INTO network_spatial_scene_revisions (network_id, revision, storage_kind, delta, "
                      "origin, actor_id) VALUES (:net, 2, 'delta', '{}', 'replacement', :net)", net=seeded.network)
    database.connection.rollback()
    run(database, "INSERT INTO network_spatial_scene_revisions (network_id, revision, storage_kind, delta, "
                  "base_revision, origin, actor_id) VALUES (:net, 2, 'delta', '{\"ops\": []}', 1, 'replacement', :net)",
        net=seeded.network)

    with pytest.raises(DBAPIError, match="Downgrade below 0030 refused"):
        command.downgrade(database.config, "0029")
    database.connection.rollback()
    assert version(database) == "0030"
    assert run(database, "SELECT to_regclass('ix_alerts_workspace_updated') IS NOT NULL")[0][0] is True


def test_downgrade_restores_renamed_keys_unless_an_execution_bound_them(database):
    command.upgrade(database.config, "0029")
    seeded = _seed_0029(database)
    command.upgrade(database.config, "head")
    first, second, third = seeded.intents
    run(database, "INSERT INTO intent_executions (execution_id, intent_id, workspace_id, org_id, request_key, "
                  "request_hash, lab_key, actor_id, approved_at, command, phase, blocks_lab, cancel_requested, "
                  "outbox_sequence, fence) VALUES (:id, :intent, :ws, :ws, :key, 'h', 'lab', 'a', now(), '{}', "
                  "'completed', false, false, 0, 1)",
        id=uuid.uuid4(), intent=third, ws=seeded.workspace, key=f"key-1~dup~{third}")
    command.downgrade(database.config, "0029")
    keys = dict(run(database, "SELECT intent_id, idempotency_key FROM intents"))
    assert keys[first] == keys[second] == "key-1"
    assert keys[third] == f"key-1~dup~{third}"  # the execution identity keeps the renamed key
    assert run(database, "SELECT column_default FROM information_schema.columns WHERE table_schema = "
                         "current_schema() AND table_name = 'devices' AND column_name = 'status'")[0][0] \
        == "'''active'''::text"


EVIDENCE = {
    "0028": ["INSERT INTO experimental_lab_resources (resource_id, fence) VALUES ('lab', 1)",
             "INSERT INTO experimental_lab_runs (run_id, resource_id, fence, policy, policy_sha256, stopped, released, "
             "phase, action_count, created_at) VALUES (gen_random_uuid(), 'lab', 1, '{}', 'x', false, false, "
             "'observing', 0, now())"],
    "0027": ["INSERT INTO autonomous_observations (observation_sha256, network_id, workspace_id, observation, "
             "safety_observation) VALUES ('x', gen_random_uuid(), gen_random_uuid(), '{}', '{}')"],
    "0022": ["INSERT INTO networks (network_id, workspace_id, name) VALUES "
             "('00000000-0000-0000-0000-000000000022', gen_random_uuid(), 'n')",
             "INSERT INTO network_spatial_scenes (network_id, revision, scene) VALUES "
             "('00000000-0000-0000-0000-000000000022', 2, '{\"objects\": []}')",
             "INSERT INTO network_spatial_scene_revisions (network_id, revision, scene, origin, actor_id) VALUES "
             "('00000000-0000-0000-0000-000000000022', 1, '{}', 'replacement', gen_random_uuid())"],
    "0018": ["INSERT INTO alerts (alert_id, alert_key, source, correlation_id) VALUES "
             "('00000000-0000-0000-0000-000000000018', 'k', 's', gen_random_uuid())",
             "INSERT INTO alert_history (event_id, alert_id, event_type, correlation_id, occurred_at, payload) VALUES "
             "(gen_random_uuid(), '00000000-0000-0000-0000-000000000018', 'alert.generated', gen_random_uuid(), "
             "now(), '{}')"],
    "0011": ["INSERT INTO intents (intent_id, workspace_id, intent_kind, correlation_id, requested_by_user_id, "
             "requested_at) VALUES ('00000000-0000-0000-0000-000000000011', gen_random_uuid(), 'x', "
             "gen_random_uuid(), 'a', now())",
             "INSERT INTO intent_executions (execution_id, intent_id, workspace_id, org_id, request_key, request_hash, "
             "lab_key, actor_id, approved_at, command, phase, blocks_lab, cancel_requested, outbox_sequence, fence) "
             "VALUES (gen_random_uuid(), '00000000-0000-0000-0000-000000000011', gen_random_uuid(), "
             "gen_random_uuid(), 'k', 'h', 'lab', 'a', now(), '{}', 'accepted', true, false, 0, 0)"],
}


@pytest.mark.parametrize("revision", sorted(EVIDENCE))
def test_historical_downgrade_refuses_while_immutable_evidence_exists(database, revision):
    command.upgrade(database.config, revision)
    for statement in EVIDENCE[revision]:
        run(database, statement)
    with pytest.raises(RuntimeError, match=f"Downgrade below {revision} refused"):
        command.downgrade(database.config, f"{int(revision) - 1:04d}")
    database.connection.rollback()
    assert version(database) == revision


def test_spatial_history_that_an_upgrade_reproduces_can_still_be_downgraded(database):
    command.upgrade(database.config, "0022")
    network = uuid.uuid4()
    run(database, "INSERT INTO networks (network_id, workspace_id, name) VALUES (:id, :id, 'n')", id=network)
    run(database, "INSERT INTO network_spatial_scenes (network_id, revision, scene) VALUES (:id, 3, '{\"a\": 1}')",
        id=network)
    run(database, "INSERT INTO network_spatial_scene_revisions (network_id, revision, scene, origin) "
                  "VALUES (:id, 3, '{\"a\": 1}', 'baseline')", id=network)
    command.downgrade(database.config, "0021")
    command.upgrade(database.config, "0022")
    assert run(database, "SELECT revision, origin FROM network_spatial_scene_revisions") == [(3, "baseline")]
